### ISSUE TITLE
ValueError: Input passed into argument "u'y1'"is not 1-dimensional.

### ISSUE THREAD

**Issue by liuhuang31** [TUT-ARG/sed_vis#2]
hi, use the demo file, it can show the picture.

But when i use the  my own data, such as b044.ann  as reference and b044_output.ann as estimated.
It happens below.

Traceback (most recent call last):
  File "vis.py", line 26, in <module>
    vis.show()
  File "/home/lhh/sed_vis/sed_vis/visualization.py", line 667, in show
    self.generate_GUI()
  File "/home/lhh/sed_vis/sed_vis/visualization.py", line 388, in generate_GUI
    color='0.5'
  File "/home/lhh/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/home/lhh/.local/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5101, in fill_between
    'is not 1-dimensional.')
ValueError: Input passed into argument "u'y1'"is not 1-dimensional.

**Comment by liuhuang31** [comment]
I find  the problem maybe is the audio file.
If I use the provided a001.wav and the reference/estimated file use myselfs, it works.
But I use the other audio file, it happens the problem, no matter what version of matplotlib I use.

**Comment by toni-heittola** [comment]
Current version only supports mono audio. Parameter `audio_signal` is assumed to be 1-dimensional numpy.array. I will update documentation to indicate this.
