### ISSUE TITLE
ModuleNotFoundError: No module named 'sed_vis.util'

### ISSUE THREAD

**Issue by Galvo87** [TUT-ARG/sed_vis#7]
Hi! After successful installation in a python 3.6 environment on Ubuntu 20.04 LTS, `visualizers/sed_visualizer.py` returns:

`Traceback (most recent call last):
  File "visualizers/sed_visualizer.py", line 10, in <module>
    import sed_vis
  File "<frozen zipimport>", line 259, in load_module
  File "/home/galvo/.virtualenvs/py36/lib/python3.8/site-packages/sed_vis-0.1.2-py3.8.egg/sed_vis/__init__.py", line 5, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/galvo/.virtualenvs/py36/lib/python3.8/site-packages/sed_vis-0.1.2-py3.8.egg/sed_vis/visualization.py", line 21, in <module>
ModuleNotFoundError: No module named 'sed_vis.util'`

Any hints? Thanks.

**Comment by chrisrauch193** [comment]
Did you get an answer for this?

**Comment by chrisrauch193** [comment]
Fixed it pretty easily you need to add the following lines to sed_vis/sed_vis.egg-info/SOURCES.txt

```
sed_vis/util/__init__.py
sed_vis/util/audio_player.py
```

**Comment by anlarro** [comment]
Hi. I'm getting this same error. Can you provide the solution?

**Comment by toni-heittola** [comment]
How did you install the `sed_vis`? Did you use the command `pip install -e sed_vis`?
